### ISSUE TITLE
build on MacOs

### ISSUE THREAD

**Issue by bwl21** [michaelforney/samurai#6]
trying to compile on macos, I got the following errors

```
> make
cc  -Wall -Wextra -std=c99 -pedantic -c -o build.o build.c
cc  -Wall -Wextra -std=c99 -pedantic -c -o env.o env.c
cc  -Wall -Wextra -std=c99 -pedantic -c -o deps.o deps.c
cc  -Wall -Wextra -std=c99 -pedantic -c -o graph.o graph.c
graph.c:86:26: error: no member named 'st_mtim' in 'struct stat'
                n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st....
                                    ~~ ^
graph.c:86:59: error: no member named 'st_mtim' in 'struct stat'
  ...n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st.st_mtim.tv_nsec;
                                                          ~~ ^
2 errors generated.

```

**Comment by evelikov** [comment]
According to `man 2 stat` it's part of the POSIX.1-2008 which is a requirement AFAICT?

**Comment by michaelforney** [comment]
Apparently MacOS names this field `st_mtimespec` and does not provide the standard name `st_mtim`.

I don't want to litter the code with ifdefs, but I think adding `-D st_mtim=st_mtimespex` to your `CFLAGS` should fix this issue.

**Comment by michaelforney** [comment]
I updated the README with a note about this. Please re-open if this does not fix the issue (or you run into other build errors on macOS).

**Comment by bwl21** [comment]
as a pity, It does not fix the issue (cannot reopen the issue for whatever reason ...)

```
$ export CFLAGS="-D st_mtim=st_mtimespec"
$ make
cc -D st_mtim=st_mtimespec -Wall -Wextra -std=c99 -pedantic -c -o graph.o graph.c
graph.c:86:26: error: no member named 'st_mtimespec' in 'struct stat'
                n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st....
                                    ~~ ^
<command line>:1:17: note: expanded from here
#define st_mtim st_mtimespec
                ^
graph.c:86:59: error: no member named 'st_mtimespec' in 'struct stat'
  ...n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st.st_mtim.tv_nsec;
                                                          ~~ ^
<command line>:1:17: note: expanded from here
#define st_mtim st_mtimespec
                ^
2 errors generated.
make: *** [graph.o] Error 1
```

Even If I have no knowledge with C, I tried 

```
$export CFLAGS="-D st_mtim=st_mtime -D _POSIX_C_SOURCE"
$make
cc -D st_mtim=st_mtime -D _POSIX_C_SOURCE -Wall -Wextra -std=c99 -pedantic -c -o graph.o graph.c
graph.c:1:9: warning: '_POSIX_C_SOURCE' macro redefined [-Wmacro-redefined]
#define _POSIX_C_SOURCE 200809L
        ^
<command line>:2:9: note: previous definition is here
#define _POSIX_C_SOURCE 1
        ^
graph.c:86:33: error: member reference base type 'time_t' (aka 'long') is not a
      structure or union
                n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st....
                                    ~~~~~~~~~~^~~~~~~
graph.c:86:66: error: member reference base type 'time_t' (aka 'long') is not a
      structure or union
  ...n->mtime = (int64_t)st.st_mtim.tv_sec * 1000000000 + st.st_mtim.tv_nsec;
                                                          ~~~~~~~~~~^~~~~~~~
1 warning and 2 errors generated.
make: *** [graph.o] Error 1
```
